version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:1337
    environment:
      - NODE_ENV=development
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  db:
    image: mongo:4.4
    restart: always
    volumes:
      - db_data:/data/db

  redis:
    image: redis:6
    restart: always
    ports:
      - 6370:6379

volumes:
  db_data: