version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8020:1337
    environment:
      - NODE_ENV=development
      - MONGO_HOST=db
      - MONGO_PORT=27017
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: always
    volumes:
      - db_data:/data/db

volumes:
  db_data: